version: '3.6'
services:
  iris:
    environment:
      - SAMPLE_TOKEN=${SAMPLE_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dtl-generator
    hostname: dtl-generator
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52795:52773
      - 53773
    volumes:
      - ./data:/data
